name: automobile_frontend
description: Automobile Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  automobile_lu_common:
    path: ../common
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.3
  pluto_grid: ^2.10.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  generate: true
