name: automobile_lu_backend
description: Automobile Backend
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  automobile_lu_common:
    path: ../common
  mongo_dart: ^0.7.4+1
  dart_jsonwebtoken: ^2.4.1
  dotenv: ^3.0.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.2
  uuid: ^3.0.6
  xml: ^6.0.1

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.1.5
